export interface UsersTable {
  id: string;
  username: string;
  discriminator?: string;
  avatar?: string;
  access_token?: string;
  refresh_token?: string;
  last_login?: Date;
  ip_address?: string;
  is_vpn?: boolean;
  last_session_created?: Date;
  last_session_deleted?: Date;
  settings?: unknown;
  settings_updated_at?: Date;
  total_sessions_created?: number;
  total_minutes?: number;
  vatsim_cid?: string | null;
  vatsim_rating_id?: number | null;
  vatsim_rating_short?: string | null;
  vatsim_rating_long?: string | null;
  created_at?: Date;
  updated_at?: Date;
  roblox_user_id?: string | null;
  roblox_username?: string | null;
  roblox_access_token?: string | null;
  roblox_refresh_token?: string | null;
  role_id?: number;
  tutorial_completed?: boolean;
  statistics?: unknown;
}
