package sessionusers

import (
	"context"
	"encoding/json"
	"sync"
	"time"

	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/bus"
	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/config"
	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/socketutil"
	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/crypto"
	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/dto"
	"github.com/PFConnect/pfcontrol-2/services/realtime/internal/store"
	"github.com/redis/go-redis/v9"
	socketio "github.com/zishang520/socket.io/servers/socket/v3"
)

type fieldKey struct {
	sessionID string
	flightID  string
	fieldName string
}

type fieldState struct {
	UserID    string  `json:"userId"`
	Username  string  `json:"username"`
	Avatar    *string `json:"avatar"`
	FlightID  string  `json:"flightId"`
	FieldName string  `json:"fieldName"`
	Timestamp int64   `json:"timestamp"`
}

func HandleConnection(
	ctx context.Context,
	cfg config.Config,
	db *store.Store,
	rdb *redis.Client,
	io *socketio.Server,
	fieldStates *sync.Map,
	client *socketio.Socket,
) {
	sessionID := socketutil.Query(client, "sessionId")
	accessID := socketutil.Query(client, "accessId")
	userJSON := socketutil.Query(client, "user")
	if sessionID == "" || accessID == "" || userJSON == "" {
		client.Disconnect(true)
		return
	}
	ok, err := store.ValidateSessionAccess(ctx, db, sessionID, accessID)
	if err != nil || !ok {
		client.Disconnect(true)
		return
	}
	var user struct {
		UserID   string  `json:"userId"`
		Username string  `json:"username"`
		Avatar   *string `json:"avatar"`
	}
	if err := json.Unmarshal([]byte(userJSON), &user); err != nil {
		client.Disconnect(true)
		return
	}
	position := socketutil.Query(client, "position")
	if position == "" {
		position = "POSITION"
	}

	sessionUser := dto.SessionUser{
		ID:       user.UserID,
		Username: user.Username,
		Avatar:   user.Avatar,
		JoinedAt: time.Now().UnixMilli(),
		Position: position,
		Roles:    []dto.UserRole{},
	}
	_ = addUser(ctx, rdb, sessionID, user.UserID, sessionUser)
	users, _ := store.GetActiveUsersForSession(ctx, rdb, sessionID)
	client.Join(socketio.Room(sessionID))
	client.Join(socketio.Room("user-" + user.UserID))
	io.To(socketio.Room(sessionID)).Emit("sessionUsersUpdate", users)

	bus.Publish(ctx, rdb, "rt:session.presence", map[string]string{"sessionId": sessionID})

	sess, _ := db.GetSessionNetwork(ctx, sessionID)
	if sess != nil {
		// ATIS from DB if present — simplified
	}

	client.On("positionChange", func(args ...any) {
		body := parseArg(args)
		if body == nil {
			return
		}
		if pos, ok := body["position"].(string); ok {
			_ = updateUserPosition(ctx, rdb, sessionID, user.UserID, pos)
			users, _ := store.GetActiveUsersForSession(ctx, rdb, sessionID)
			io.To(socketio.Room(sessionID)).Emit("sessionUsersUpdate", users)
			bus.Publish(ctx, rdb, "rt:session.presence", map[string]string{"sessionId": sessionID})
		}
	})

	client.On("fieldEditingStart", func(args ...any) {
		body := parseArg(args)
		if body == nil {
			return
		}
		fid := stringVal(body["flightId"])
		fname := stringVal(body["fieldName"])
		key := fieldKey{sessionID, fid, fname}
		fieldStates.Store(key, fieldState{
			UserID: user.UserID, Username: user.Username, Avatar: user.Avatar,
			FlightID: fid, FieldName: fname, Timestamp: time.Now().UnixMilli(),
		})
		broadcastFieldEditing(io, fieldStates, sessionID)
	})

	client.On("fieldEditingStop", func(args ...any) {
		body := parseArg(args)
		if body == nil {
			return
		}
		fid := stringVal(body["flightId"])
		fname := stringVal(body["fieldName"])
		key := fieldKey{sessionID, fid, fname}
		if v, ok := fieldStates.Load(key); ok {
			if st, ok := v.(fieldState); ok && st.UserID == user.UserID {
				fieldStates.Delete(key)
			}
		}
		broadcastFieldEditing(io, fieldStates, sessionID)
	})

	client.On("atisGenerated", func(args ...any) {
		body := parseArg(args)
		if body == nil {
			return
		}
		atisPayload, _ := body["atis"]
		enc, err := crypto.EncryptATIS(cfg.EncryptionKey, atisPayload)
		if err != nil {
			return
		}
		raw, _ := json.Marshal(enc)
		_, _ = db.Pool.Exec(ctx, `UPDATE sessions SET atis = $1 WHERE session_id = $2`, string(raw), sessionID)
		io.To(socketio.Room(sessionID)).Emit("atisUpdate", map[string]interface{}{
			"atis":            atisPayload,
			"updatedBy":       user.Username,
			"isAutoGenerated": false,
		})
		bus.Publish(ctx, rdb, "rt:session.atis", map[string]string{"sessionId": sessionID})
	})

	client.On("disconnect", func(...any) {
		_ = removeUser(ctx, rdb, sessionID, user.UserID)
		users, _ := store.GetActiveUsersForSession(ctx, rdb, sessionID)
		io.To(socketio.Room(sessionID)).Emit("sessionUsersUpdate", users)
		bus.Publish(ctx, rdb, "rt:session.presence", map[string]string{"sessionId": sessionID})
	})
}

func addUser(ctx context.Context, rdb *redis.Client, sessionID, userID string, u dto.SessionUser) error {
	b, err := json.Marshal(u)
	if err != nil {
		return err
	}
	return rdb.HSet(ctx, "activeUsers:"+sessionID, userID, b).Err()
}

func removeUser(ctx context.Context, rdb *redis.Client, sessionID, userID string) error {
	key := "activeUsers:" + sessionID
	if err := rdb.HDel(ctx, key, userID).Err(); err != nil {
		return err
	}
	n, _ := rdb.HLen(ctx, key).Result()
	if n == 0 {
		_ = rdb.Del(ctx, key).Err()
	}
	return nil
}

func updateUserPosition(ctx context.Context, rdb *redis.Client, sessionID, userID, position string) error {
	raw, err := rdb.HGet(ctx, "activeUsers:"+sessionID, userID).Result()
	if err != nil {
		return err
	}
	var u dto.SessionUser
	if json.Unmarshal([]byte(raw), &u) != nil {
		return err
	}
	u.Position = position
	return addUser(ctx, rdb, sessionID, userID, u)
}

func broadcastFieldEditing(io *socketio.Server, states *sync.Map, sessionID string) {
	arr := []fieldState{}
	states.Range(func(key, value interface{}) bool {
		k, ok := key.(fieldKey)
		if !ok || k.sessionID != sessionID {
			return true
		}
		if st, ok := value.(fieldState); ok {
			arr = append(arr, st)
		}
		return true
	})
	io.To(socketio.Room(sessionID)).Emit("fieldEditingUpdate", arr)
}

func parseArg(args []any) map[string]interface{} {
	if len(args) == 0 {
		return nil
	}
	if m, ok := args[0].(map[string]interface{}); ok {
		return m
	}
	return nil
}

func stringVal(v interface{}) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}
