export const S = {
  card: 'bg-zinc-900 border border-zinc-700/50 rounded-2xl overflow-hidden',
  header: 'w-full p-4 sm:p-6 border-b border-zinc-700/50',
  headerInner: 'flex items-center justify-between gap-3',
  headerClickable: 'flex items-center flex-1 min-w-0 cursor-pointer',
  iconBox: 'p-2 rounded-lg flex-shrink-0',
  iconBoxMr: 'mr-3 sm:mr-4',
  icon: 'h-5 w-5 sm:h-6 sm:w-6',
  title: 'text-lg sm:text-xl font-semibold text-white',
  subtitle: 'text-zinc-400 text-xs sm:text-sm mt-1 hidden sm:block',
  content: 'p-4 sm:p-6',
  section: 'bg-zinc-800/30 border border-zinc-700/50 rounded-xl p-5',
  sectionHeader: 'flex items-start mb-4',
  sectionIconBox: 'p-2 rounded-lg mr-4 mt-0.5 flex-shrink-0',
  sectionIcon: 'h-5 w-5',
  sectionTitle: 'text-white font-medium mb-1',
  sectionSubtitle: 'text-zinc-400 text-sm',
  toggleRow: 'flex items-center justify-between p-4 bg-zinc-900/50 rounded-lg border border-zinc-700/30',
  infoBanner: 'mt-6 p-4 border rounded-lg',
  chevronBtn: 'border-zinc-600 text-zinc-300 hover:bg-zinc-800 p-2 flex-shrink-0',
} as const;